import { Event, BlogPost, Testimonial, VenueSpace, FAQ } from "@/lib/types";

export const featuredEvents: Event[] = [
  {
    id: "1",
    title: "MARC LAVOINE SYMPHONIQUE",
    description: "Marc Lavoine presents his symphonic show, combining his greatest hits with orchestral arrangements.",
    image: "https://apps.ticketmatic.com/obj/filestore/prod/10491/events/11128/image.667145b974770.480.jpg",
    date: "2025-04-24",
    time: "19:00",
    venue: "Main Hall",
    category: "French Pop",
    price: "€45 - €75",
  },
  {
    id: "2",
    title: "MIKI",
    description: "Rising French pop star MIKI performs her latest hits.",
    image: "https://images.pexels.com/photos/811838/pexels-photo-811838.jpeg",
    date: "2025-04-25",
    time: "20:00",
    venue: "Floor",
    category: "French Pop",
    price: "€35",
  },
  {
    id: "3",
    title: "J.B.O",
    description: "German metal band J.B.O brings their unique style to Rockhal.",
    image: "https://images.pexels.com/photos/1190297/pexels-photo-1190297.jpeg",
    date: "2025-04-26",
    time: "19:00",
    venue: "Club",
    category: "Metal",
    price: "€30",
  },
  {
    id: "4",
    title: "JEFF GOLDBLUM & THE MILDRED SNITZER ORCHESTRA",
    description: "An evening of jazz with Jeff Goldblum and his orchestra.",
    image: "https://images.pexels.com/photos/1293269/pexels-photo-1293269.jpeg",
    date: "2025-04-26",
    time: "19:00",
    venue: "Main Hall",
    category: "Blues/Jazz",
    price: "€55 - €85",
  },
  {
    id: "5",
    title: "LE LAC DES CYGNES",
    description: "The timeless ballet masterpiece performed live.",
    image: "https://images.pexels.com/photos/1916821/pexels-photo-1916821.jpeg",
    date: "2025-04-27",
    time: "14:30",
    venue: "Main Hall",
    category: "Entertainment",
    price: "€40 - €70",
  },
  {
    id: "6",
    title: "PRAETOR",
    description: "Heavy metal band PRAETOR live in concert.",
    image: "https://images.pexels.com/photos/2078071/pexels-photo-2078071.jpeg",
    date: "2025-05-02",
    time: "20:00",
    venue: "Club",
    category: "Metal",
    price: "€25",
  },
  {
    id: "7",
    title: "DEBORAH DE LUCA",
    description: "International techno DJ Deborah De Luca.",
    image: "https://images.pexels.com/photos/1749822/pexels-photo-1749822.jpeg",
    date: "2025-05-03",
    time: "21:00",
    venue: "Club",
    category: "Electro/Clubbing",
    price: "€30",
    soldOut: true,
  },
  {
    id: "8",
    title: "TONY ANN",
    description: "Classical pianist Tony Ann in concert.",
    image: "https://images.pexels.com/photos/236149/pexels-photo-236149.jpeg",
    date: "2025-05-04",
    time: "16:00",
    venue: "Club",
    category: "Classical",
    price: "€35",
  },
  {
    id: "9",
    title: "FELIX LOBRECHT",
    description: "Comedy show with Felix Lobrecht.",
    image: "https://images.pexels.com/photos/236149/pexels-photo-236149.jpeg",
    date: "2025-05-04",
    time: "17:30",
    venue: "Main Hall",
    category: "Entertainment",
    price: "€35",
    soldOut: true,
  },
  {
    id: "10",
    title: "THE LUMINEERS",
    description: "Folk-rock band The Lumineers live in concert.",
    image: "https://images.pexels.com/photos/236149/pexels-photo-236149.jpeg",
    date: "2025-05-06",
    time: "19:00",
    venue: "Box",
    category: "Pop",
    price: "€45",
  },
  {
    id: "40",
    title: "THE BLACK KEYS",
    description: "Rock duo The Black Keys performing live.",
    image: "https://images.pexels.com/photos/236149/pexels-photo-236149.jpeg",
    date: "2025-06-29",
    time: "19:00",
    venue: "Main Hall",
    category: "Rock",
    price: "€55 - €85",
  },
];

export const blogPosts: BlogPost[] = [
  {
    id: "1",
    title: "Behind the Scenes: Setting Up for Major Concerts",
    excerpt: "Ever wondered what goes into preparing for a major concert? We take you backstage to reveal the complex process that happens before the artists even arrive.",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget ultricies aliquam, nunc nisl aliquet nunc, eget aliquam nisl nunc eget nisl. Nulla euismod, nisl eget ultricies aliquam, nunc nisl aliquet nunc, eget aliquam nisl nunc eget nisl.",
    image: "https://images.pexels.com/photos/2747446/pexels-photo-2747446.jpeg",
    date: "2025-03-15",
    author: "Thomas Weber",
    category: "Behind the Scenes",
    featured: true,
  },
  {
    id: "2",
    title: "Interview: Rising Star Emma Keller on Her Debut Album",
    excerpt: "We sat down with Emma Keller before her sold-out show at Rockhal to discuss her journey, creative process, and the success of her debut album.",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget ultricies aliquam, nunc nisl aliquet nunc, eget aliquam nisl nunc eget nisl. Nulla euismod, nisl eget ultricies aliquam, nunc nisl aliquet nunc, eget aliquam nisl nunc eget nisl.",
    image: "https://images.pexels.com/photos/3052360/pexels-photo-3052360.jpeg",
    date: "2025-03-10",
    author: "Sophie Martin",
    category: "Interviews",
    featured: true,
  },
  {
    id: "3",
    title: "Concert Review: Imagine Dragons Electrify Rockhal",
    excerpt: "Our review of Imagine Dragons' explosive performance that had the entire audience on their feet from start to finish. A night to remember!",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget ultricies aliquam, nunc nisl aliquet nunc, eget aliquam nisl nunc eget nisl. Nulla euismod, nisl eget ultricies aliquam, nunc nisl aliquet nunc, eget aliquam nisl nunc eget nisl.",
    image: "https://images.pexels.com/photos/1105666/pexels-photo-1105666.jpeg",
    date: "2025-03-05",
    author: "Jean Dupont",
    category: "Reviews",
    featured: true,
  },
  {
    id: "4",
    title: "The Evolution of Music Venues: From Halls to Experiences",
    excerpt: "How music venues have transformed from simple concert halls to comprehensive entertainment experiences, and what this means for artists and audiences.",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget ultricies aliquam, nunc nisl aliquet nunc, eget aliquam nisl nunc eget nisl. Nulla euismod, nisl eget ultricies aliquam, nunc nisl aliquet nunc, eget aliquam nisl nunc eget nisl.",
    image: "https://images.pexels.com/photos/2263436/pexels-photo-2263436.jpeg",
    date: "2025-02-28",
    author: "Marie Schmidt",
    category: "Industry Insights",
    featured: false,
  },
  {
    id: "5",
    title: "Sustainable Concerts: How Rockhal Is Going Green",
    excerpt: "Discover the initiatives Rockhal is implementing to reduce its environmental impact and create more sustainable live music experiences.",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget ultricies aliquam, nunc nisl aliquet nunc, eget aliquam nisl nunc eget nisl. Nulla euismod, nisl eget ultricies aliquam, nunc nisl aliquet nunc, eget aliquam nisl nunc eget nisl.",
    image: "https://images.pexels.com/photos/957024/forest-trees-perspective-bright-957024.jpeg",
    date: "2025-02-20",
    author: "Luc Meyer",
    category: "Sustainability",
    featured: false,
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "1",
    name: "David Mitchell",
    role: "Lead singer, The Echoes",
    content: "One of the best venues I've performed at. The acoustics are incredible, and the staff goes above and beyond to make artists feel welcome.",
    rating: 5,
  },
  {
    id: "2",
    name: "Sophie Dubois",
    role: "Concert enthusiast",
    content: "I've attended concerts at venues across Europe, and Rockhal stands out for its amazing sound quality and atmosphere. A must-visit for music lovers!",
    rating: 5,
  },
  {
    id: "3",
    name: "Marc Weber",
    role: "Local music journalist",
    content: "The facilities are top-notch, and the variety of events is impressive. From metal concerts to classical performances, Rockhal has something for everyone.",
    rating: 5,
  },
  {
    id: "4",
    name: "Julia Schmidt",
    role: "Tour manager",
    content: "From a logistical standpoint, Rockhal is a dream to work with. Their professional crew and well-designed loading areas make setup and teardown efficient.",
    rating: 5,
  },
];

export const venueSpaces: VenueSpace[] = [
  {
    id: "1",
    name: "Main Hall",
    capacity: "6,500 standing",
    description: "Our largest space, perfect for major international acts and large-scale productions. Features state-of-the-art sound systems and lighting rigs.",
    image: "https://images.pexels.com/photos/1470720/pexels-photo-1470720.jpeg",
  },
  {
    id: "2",
    name: "Club",
    capacity: "1,200 standing",
    description: "An intimate setting ideal for emerging artists and more personal performances. Excellent acoustics and a vibrant atmosphere.",
    image: "https://images.pexels.com/photos/1540406/pexels-photo-1540406.jpeg",
  },
  {
    id: "3",
    name: "Floor",
    capacity: "300 seated",
    description: "A versatile space for workshops, small performances, and special events. Can be configured in various layouts.",
    image: "https://images.pexels.com/photos/3184183/pexels-photo-3184183.jpeg",
  },
  {
    id: "4",
    name: "Rockhal Café",
    capacity: "150 seated",
    description: "A casual dining space serving food and drinks before and after events. Also hosts acoustic sets and small performances.",
    image: "https://images.pexels.com/photos/2788792/pexels-photo-2788792.jpeg",
  },
];

export const faqs: FAQ[] = [
  {
    question: "What time do doors open for concerts?",
    answer: "Doors typically open 1 hour before the scheduled start time of the concert. The exact opening time is always indicated on your ticket and on our website event page.",
    category: "Tickets & Entry",
  },
  {
    question: "Is there parking available at Rockhal?",
    answer: "Yes, Rockhal has a large parking area with over 900 spaces. Parking is free for event attendees. On busier nights, we recommend arriving early to secure a spot.",
    category: "Venue Information",
  },
  {
    question: "Can I bring a camera to events?",
    answer: "Small personal cameras are usually permitted, but professional cameras (with detachable lenses) and recording equipment are generally not allowed unless specifically authorized. Policy may vary by event, so please check the specific event page for details.",
    category: "Event Rules",
  },
  {
    question: "What items are prohibited at Rockhal?",
    answer: "Prohibited items include outside food and drinks, large bags, professional cameras, recording equipment, and any dangerous items. A full list of prohibited items is available on our website and may vary by event.",
    category: "Event Rules",
  },
  {
    question: "Is there a coat check available?",
    answer: "Yes, Rockhal provides a coat check service for a small fee. The coat check is located in the main entrance area.",
    category: "Venue Information",
  },
  {
    question: "Are there food and drink options available?",
    answer: "Yes, Rockhal has several bars serving a variety of drinks, and the Rockhal Café offers food options before and after shows. Opening hours of food services may vary depending on the event.",
    category: "Amenities",
  },
  {
    question: "What is your refund policy?",
    answer: "Tickets are generally non-refundable unless an event is cancelled. If an event is postponed, tickets will usually be valid for the rescheduled date. For specific situations, please contact our customer service team.",
    category: "Tickets & Entry",
  },
  {
    question: "Is Rockhal accessible for people with disabilities?",
    answer: "Yes, Rockhal is fully accessible with designated spaces for wheelchair users, accessible toilets, and entrances. Please contact us in advance if you require any specific accommodations.",
    category: "Accessibility",
  },
];